name: evdesaglik
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  flutter_local_notifications: ^14.1.1
  cached_network_image: ^3.2.3
  firebase_messaging: ^14.6.2
  another_flushbar: ^1.12.30
  cloud_firestore: ^4.8.0
  table_calendar: ^3.0.9
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/Metropolis-Bold.otf
    - family: extra
      fonts:
        - asset: assets/fonts/Metropolis-ExtraBold.otf
    - family: medium
      fonts:
        - asset: assets/fonts/Metropolis-Medium.otf
    - family: semi
      fonts:
        - asset: assets/fonts/Metropolis-SemiBold.otf